database:
  db_host: ":memory:"
  tables:
    intervals:
      table_name: intervals
      columns:
        - column_name: id
          data_type: INTEGER
          primary_key: true
          auto_increment: true
        - column_name: name
          data_type: TEXT
        - column_name: seconds
          data_type: INTEGER
        - column_name: short_suffix
          data_type: TEXT
        - column_name: medium_suffix
          data_type: TEXT
      unique_constraints:
        - - name
          - seconds
    groups:
      table_name: groups
      columns:
        - column_name: id
          data_type: INTEGER
          primary_key: true
          auto_increment: true
        - column_name: name
          data_type: TEXT
      unique_constraints:
        - - name
    timewise_values:
      table_name: timewise_values
      columns:
        - column_name: id
          data_type: INTEGER
          primary_key: true
          auto_increment: true
        - column_name: key
          data_type: TEXT
        - column_name: value
          data_type: TEXT
        - column_name: group_id
          data_type: INTEGER
      unique_constraints:
        - - key
      foreign_keys:
        - column: group_id
          references: groups
          ref_column: id
    tasks:
      table_name: tasks
      columns:
        - column_name: id
          data_type: INTEGER
          primary_key: true
          auto_increment: true
        - column_name: title
          data_type: TEXT
        - column_name: description
          data_type: TEXT
          allow_null: true
        - column_name: status_id
          data_type: INTEGER
        - column_name: category_id
          data_type: INTEGER
        - column_name: priority
          data_type: INTEGER
        - column_name: estimated_time
          data_type: INTEGER
          allow_null: true
        - column_name: time_spent
          data_type: INTEGER
          allow_null: true
        - column_name: due_date
          data_type: TEXT
          allow_null: true
        - column_name: start_date
          data_type: TEXT
          allow_null: true
        - column_name: completed
          data_type: INTEGER
      foreign_keys:
        - column: category_id
          references: categories
          ref_column: id
        - column: status_id
          references: statuses
          ref_column: id
      check_constraints:
        - constraint: priority
          operator: ">="
          value: "0"
  initial_values:
    groups:
      - name: tag
      - name: category
      - name: setting
      - name: custom_field
      - name: status
    timewise_values:
      - key: priority_min
        value: "0"
      - key: priority_max
        value: "5"
      - key: work
        value: "Work"
      - key: personal
        value: "Personal"
      - key: open
        value: "Open"
      - key: in_progress
        value: "InProgress"
      - key: on_hold
        value: "OnHold"
      - key: completed
        value: "Completed"
      - key: canceled
        value: "Canceled"
        group_id:
          table_name: groups
          columns:
            - id
          conditions:
            name: "status"
    intervals:
      - name: second
        seconds: 1
        short_suffix: "s"
        medium_suffix: "sec"
      - name: minute
        seconds: 60
        short_suffix: "m"
        medium_suffix: "min"
      - name: hour
        seconds: 3600
        short_suffix: "h"
        medium_suffix: "hr"
      - name: day
        seconds: 86400
        short_suffix: "d"
        medium_suffix: "day"
      - name: week
        seconds: 604800
        short_suffix: "w"
        medium_suffix: "wk"
      - name: month
        seconds: 2592000
        short_suffix: "mo"
        medium_suffix: "mon"
      - name: year
        seconds: 31536000
        short_suffix: "y"
        medium_suffix: "yr"
  views:
    - view_name: tags
      source: timewise_values
      filter: "group_id = (SELECT id FROM groups WHERE key = 'tag')"
    - view_name: categories
      source: timewise_values
      filter: "group_id = (SELECT id FROM groups WHERE key = 'category')"
    - view_name: settings
      source: timewise_values
      filter: "group_id = (SELECT id FROM groups WHERE key = 'setting')"
    - view_name: custom_fields
      source: timewise_values
      filter: "group_id = (SELECT id FROM groups WHERE key = 'custom_field')"
    - view_name: statuses
      source: timewise_values
      filter: "group_id = (SELECT id FROM groups WHERE key = 'status')"
    - view_name: priorities
      source: timewise_values
      filter: "group_id = (SELECT id FROM groups WHERE key = 'priority')"
