initial_values:
  categories:
    - name: "Other"
      color: "#000000"
      description: "Default category, used when no category is specified"
    - name: "Food"
      color: "#FF0000"
      description: "All food related tasks"
    - name: "Transport"
      color: "#00FF00"
      description: "All transport related tasks"
    - name: "Entertainment"
      color: "#0000FF"
      description: "All entertainment related tasks"
    - name: "Health"
      color: "#FFFF00"
      description: "All health related tasks"
    - name: "Education"
      color: "#00FFFF"
      description: "All education related tasks"
    - name: "Gifts"
      color: "#FF00FF"
      description: "All gift related tasks"
    - name: "Clothes"
      color: "#FFFFFF"
      description: "All clothes related tasks"
    - name: "Bills"
      color: "#FFA500"
      description: "All bills related tasks"
    - name: "Economy"
      color: "#A52A2A"
      description: "All economy related tasks"
    - name: "Cleaning"
      color: "#008000"
      description: "All cleaning related tasks"
  tags:
    - name: "Sandra"
    - name: "Thea"
    - name: "Mum"
    - name: "Dad"
    - name: "Friends"
    - name: "Bike"
    - name: "Car"
    - name: "Running"
  settings:
    - key: "default_priority"
      value: 3
    - key: "default_category"
      value: "Other"
    - key: "default_sort_method"
      value: "by_priority"
    - key: "default_sort_order"
      value: "asc"
    - key: "default_task_display_columns"
      value: "id, name, description, category, priority, due_time"
